# Generated by Django 4.2.5 on 2023-10-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_kost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kost', models.CharField(max_length=100)),
                ('code_kost', models.CharField(max_length=100)),
                ('rfid', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
