# Generated by Django 4.2.5 on 2023-10-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_kost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('code_user', models.IntegerField(max_length=100)),
                ('tag_id', models.IntegerField()),
                ('telepon', models.IntegerField()),
                ('alamat', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='data_kost',
            name='rfid',
        ),
        migrations.AlterField(
            model_name='data_kost',
            name='code_kost',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='data_kost',
            name='nama_kost',
            field=models.CharField(max_length=255),
        ),
    ]
