# Generated by Django 4.2.5 on 2023-10-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_user_kost_remove_data_kost_rfid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_kost',
            name='code_kost',
            field=models.IntegerField(),
        ),
    ]
