# Generated by Django 4.2.5 on 2023-10-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_user_kost_code_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_kost',
            name='nomor_kost',
            field=models.IntegerField(default=0),
        ),
    ]
