# Generated by Django 4.2.5 on 2023-10-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_data_kost_nomor_kost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_kost',
            name='nomor_kost',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
