# Generated by Django 4.2.5 on 2023-10-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_data_kost_nomor_kost'),
    ]

    operations = [
        migrations.CreateModel(
            name='kost_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kost', models.CharField(max_length=255)),
                ('nomor_kost', models.CharField(default=0, max_length=50)),
                ('unique_id', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tag_rfid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.IntegerField()),
                ('unique_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='user_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('unique_id', models.IntegerField()),
                ('telepon', models.BigIntegerField()),
                ('alamat', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='data_kost',
        ),
        migrations.DeleteModel(
            name='user_kost',
        ),
    ]
