# Generated by Django 4.2.5 on 2023-10-29 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_kost_member_tag_rfid_user_member_delete_data_kost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_member',
            name='telepon',
            field=models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999)]),
        ),
    ]
