# Generated by Django 4.2.5 on 2023-11-03 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_user_member_telepon'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag_rfid',
            name='attandence',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kost_member',
            name='nomor_kost',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kost_member',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='open', max_length=100),
        ),
        migrations.AlterField(
            model_name='user_member',
            name='telepon',
            field=models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(999999999999), django.core.validators.MinValueValidator(9999999999)]),
        ),
    ]
