# Generated by Django 4.2.5 on 2023-11-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_tag_rfid_attandence_alter_kost_member_nomor_kost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag_rfid',
            name='unique_id',
            field=models.BigIntegerField(),
        ),
    ]
