# Generated by Django 4.2.5 on 2023-11-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_tag_rfid_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_member',
            name='tag_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kost_member',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='close', max_length=100),
        ),
    ]
