# Generated by Django 4.2.5 on 2023-11-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_user_member_tag_id_alter_kost_member_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_member',
            name='tag_id',
            field=models.BigIntegerField(),
        ),
    ]
