# Generated by Django 4.2.5 on 2023-11-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_user_member_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_member',
            name='alamat',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
