# Generated by Django 4.2.5 on 2023-11-08 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_user_member_alamat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tag_rfid',
        ),
    ]
